version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.15.0
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
    volumes:
      - ./data:/var/lib/weaviate

