name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
        build-args: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Ensure the directory exists and is empty
          mkdir -p /path/to/server
          rm -rf /path/to/server/*
          # Clone the repository
          git clone https://github.com/${{ secrets.REPOSITORY_PATH }} /path/to/server
          # Navigate to the project directory
          cd /path/to/server
          # Checkout the main branch
          git checkout main
          # Pull the latest changes
          git pull origin main
          # Run Docker Compose
          docker-compose down
          docker-compose up --build
